//! Per-subcommand handlers. `main::run` is a thin dispatcher over these.

pub(crate) mod agent;
pub(crate) mod ci;
pub(crate) mod context;
pub(crate) mod dispatch;
pub(crate) mod doctor;
pub(crate) mod graph;
pub(crate) mod hook;
pub(crate) mod init;
pub(crate) mod insight;
pub(crate) mod issue;
pub(crate) mod memory_banking;
pub(crate) mod pin;
pub(crate) mod pipeline;
pub(crate) mod plan;
pub(crate) mod policy;
pub(crate) mod release;
pub(crate) mod review;
pub(crate) mod scaffold;
pub(crate) mod session;
pub(crate) mod skill;
pub(crate) mod status;
pub(crate) mod task;
pub(crate) mod test_check;
pub(crate) mod verify;
pub(crate) mod wave;
pub(crate) mod workflow;
pub(crate) mod worktree;

pub(crate) use agent::run_agent_action;
pub(crate) use ci::run_ci_action;
pub(crate) use context::run_context;
pub(crate) use dispatch::run_dispatch;
pub(crate) use doctor::run_doctor_cmd;
pub(crate) use graph::{run_graph_action, run_visualize_graph};
pub(crate) use hook::run_hook_action;
pub(crate) use init::run_init_cmd;
pub(crate) use insight::run_insight_action;
pub(crate) use issue::run_issue_action;
pub(crate) use memory_banking::run_memory_banking_action;
pub(crate) use pin::{run_pin, run_unpin};
pub(crate) use pipeline::run_pipeline_action;
pub(crate) use plan::run_plan_action;
pub(crate) use policy::run_policy_action;
pub(crate) use release::run_release_action;
pub(crate) use review::run_review_action;
pub(crate) use scaffold::run_scaffold;
pub(crate) use session::{run_handoff, run_handon, run_session_action};
pub(crate) use skill::run_skill_action;
pub(crate) use status::run_status;
pub(crate) use task::run_task_action;
pub(crate) use test_check::run_test_check;
pub(crate) use verify::run_verify;
pub(crate) use wave::run_wave_action;
pub(crate) use workflow::run_workflow_action;
pub(crate) use worktree::run_worktree_action;
