// Generated by `godmode hook generate --client opencode`. Do not edit.
//
// Ports the godmode hook surface to OpenCode. Claude's `PreToolUse` and
// `PostToolUse` become `tool.execute.before` / `tool.execute.after`.
//
// Claude's `SessionStart` and `Stop` have no OpenCode equivalent, so the
// hooks on those events do not run here. UNMAPPED lists them; the warning
// below fires once at plugin load rather than failing silently.

import type { Plugin } from "@opencode-ai/plugin"

const PLUGIN_ROOT =
  process.env.CLAUDE_PLUGIN_ROOT ?? process.env.GODMODE_PLUGIN_ROOT ?? process.cwd()

/** Claude hooks with no OpenCode lifecycle counterpart. */
const UNMAPPED: { id: string; event: string; command: string }[] = [
  {
    "command": "godmode hook run introspection",
    "event": "Stop",
    "id": "introspection"
  },
  {
    "command": "nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/memory-bank-inject.nu",
    "event": "SessionStart",
    "id": "memory-bank-inject"
  },
  {
    "command": "nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/memory-bank-update-remind.nu",
    "event": "Stop",
    "id": "memory-bank-update-remind"
  },
  {
    "command": "rust-script $CLAUDE_PLUGIN_ROOT/hooks/scripts/session-start.rs",
    "event": "SessionStart",
    "id": "session-start"
  },
  {
    "command": "godmode hook run stop-guard",
    "event": "Stop",
    "id": "stop-guard"
  },
  {
    "command": "godmode hook run task-management",
    "event": "SessionStart",
    "id": "task-management"
  }
]

/**
 * Run a godmode hook script with the OpenCode tool payload on stdin.
 *
 * The scripts keep the Claude contract: JSON on stdin, advisory text on
 * stdout, exit code 0 to allow. Failures are reported but never block the
 * tool call, matching Claude's behaviour for the `godmode hook run` hooks.
 */
async function run(command: string, timeout: number): Promise<void> {
  const argv = command.replaceAll("$CLAUDE_PLUGIN_ROOT", PLUGIN_ROOT).split(" ")
  try {
    const proc = Bun.spawn(argv, {
      stdin: "pipe",
      stdout: "pipe",
      stderr: "pipe",
      env: { ...process.env, CLAUDE_PLUGIN_ROOT: PLUGIN_ROOT },
    })
    proc.stdin.write(JSON.stringify(TOOL_PAYLOAD))
    proc.stdin.end()
    const timer = setTimeout(() => proc.kill(), timeout * 1000)
    await proc.exited
    clearTimeout(timer)
  } catch (error) {
    console.error(`[godmode] hook failed: ${command} (${error})`)
  }
}

let TOOL_PAYLOAD: unknown = {}

export const GodmodePlugin: Plugin = async () => {
  if (UNMAPPED.length > 0) {
    console.warn(
      `[godmode] ${UNMAPPED.length} Claude hook(s) have no OpenCode equivalent and will not run: ` +
        UNMAPPED.map((h) => `${h.id} (${h.event})`).join(", "),
    )
  }

  return {
    "tool.execute.before": async (input) => {
      TOOL_PAYLOAD = input
      const tool = input.tool
    if (tool === "bash") {
      await run("nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/pre-bash-nag.nu", 10)
      await run("nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/pre-commit-gate.nu", 30)
      await run("godmode hook run moa", 10)
    }
    if (tool === "task") {
      await run("nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/pre-agent-task-context.nu", 10)
      await run("godmode hook run agent-governance", 10)
    }
    if (tool === "write") {
      await run("godmode hook run brainstorm", 10)
    }
    },
    "tool.execute.after": async (input) => {
      TOOL_PAYLOAD = input
      const tool = input.tool
    if (tool === "bash") {
      await run("nu $CLAUDE_PLUGIN_ROOT/hooks/task-done-sync.nu", 15)
      await run("nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/post-pipeline-step.nu", 10)
      await run("godmode hook run auto-block", 10)
      await run("godmode hook run ci-fix", 15)
      await run("godmode hook run code-review", 10)
      await run("godmode hook run wave-integration", 10)
    }
    if (tool === "edit") {
      await run("nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/post-json-validate.nu", 10)
      await run("nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/post-toml-validate.nu", 10)
      await run("nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/post-yaml-validate.nu", 10)
      await run("nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/post-nu-check.nu", 10)
    }
    if (tool === "task") {
      await run("bash $CLAUDE_PLUGIN_ROOT/hooks/scripts/check-blocked.sh", 10)
      await run("godmode hook run parallel-agents", 10)
    }
    if (tool === "write") {
      await run("nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/post-json-validate.nu", 10)
      await run("nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/post-toml-validate.nu", 10)
      await run("nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/post-yaml-validate.nu", 10)
      await run("nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/post-nu-check.nu", 10)
      await run("rust-script $CLAUDE_PLUGIN_ROOT/hooks/scripts/post-write-plan-ingest.rs", 15)
    }
    },
  }
}

