// Generated by `godmode hook generate --client opencode`. Do not edit.
//
// Ports the godmode hook surface to OpenCode. Claude's `PreToolUse` and
// `PostToolUse` become `tool.execute.before` / `tool.execute.after`.
//
// Claude's `SessionStart` and `Stop` have no OpenCode equivalent, so the
// hooks on those events do not run here. UNMAPPED lists them; the warning
// below fires once at plugin load rather than failing silently.

import type { Plugin } from "@opencode-ai/plugin"

const PLUGIN_ROOT =
  process.env.CLAUDE_PLUGIN_ROOT ?? process.env.GODMODE_PLUGIN_ROOT ?? process.cwd()

/** Claude hooks with no OpenCode lifecycle counterpart. */
const UNMAPPED: { id: string; event: string; command: string }[] = [
  {
    "command": "godmode hook run introspection",
    "event": "Stop",
    "id": "introspection"
  },
  {
    "command": "nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/memory-bank-inject.nu",
    "event": "SessionStart",
    "id": "memory-bank-inject"
  },
  {
    "command": "nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/memory-bank-update-remind.nu",
    "event": "Stop",
    "id": "memory-bank-update-remind"
  },
  {
    "command": "rust-script $CLAUDE_PLUGIN_ROOT/hooks/scripts/session-start.rs",
    "event": "SessionStart",
    "id": "session-start"
  },
  {
    "command": "godmode hook run stop-guard",
    "event": "Stop",
    "id": "stop-guard"
  },
  {
    "command": "godmode hook run task-management",
    "event": "SessionStart",
    "id": "task-management"
  }
]

/** A Claude PreToolUse decision, as printed by the hook scripts. */
type Decision = { decision: "approve" | "block"; reason?: string }

/**
 * Run a godmode hook script with the OpenCode tool payload on stdin and
 * return its Claude-style decision.
 *
 * Scripts keep the Claude contract: JSON on stdin, a
 * `{"decision": "approve" | "block", ...}` document on stdout. Unparseable
 * or absent output is treated as approve, because a hook that cannot be
 * understood must not wedge the tool.
 */
async function decide(command: string, timeout: number, payload: unknown): Promise<Decision | undefined> {
  const argv = command.replaceAll("$CLAUDE_PLUGIN_ROOT", PLUGIN_ROOT).split(" ")
  try {
    const proc = Bun.spawn(argv, {
      stdin: "pipe",
      stdout: "pipe",
      stderr: "pipe",
      env: { ...process.env, CLAUDE_PLUGIN_ROOT: PLUGIN_ROOT },
    })
    proc.stdin.write(JSON.stringify(payload))
    proc.stdin.end()
    const timer = setTimeout(() => proc.kill(), timeout * 1000)
    const [, stdout] = await Promise.all([proc.exited, new Response(proc.stdout).text()])
    clearTimeout(timer)
    const verdict = stdout.match(/\{[^{}]*"decision"[^{}]*\}/)
    if (!verdict) return undefined
    return JSON.parse(verdict[0]) as Decision
  } catch (error) {
    console.error(`[godmode] hook failed: ${command} (${error})`)
    return undefined
  }
}

/** PostToolUse hooks are advisory: they report, they never block. */
async function run(command: string, timeout: number, payload: unknown): Promise<void> {
  await decide(command, timeout, payload)
}

export const GodmodePlugin: Plugin = async () => {
  if (UNMAPPED.length > 0) {
    console.warn(
      `[godmode] ${UNMAPPED.length} Claude hook(s) have no OpenCode equivalent and will not run: ` +
        UNMAPPED.map((h) => `${h.id} (${h.event})`).join(", "),
    )
  }

  return {
    "tool.execute.before": async (input, output) => {
      const tool = input.tool
      const payload = { ...input, ...output }
      let verdict: Decision | undefined
      if (tool === "bash") {
        verdict ??= await decide("nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/pre-bash-nag.nu", 10, payload)
        verdict ??= await decide("nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/pre-commit-gate.nu", 30, payload)
        verdict ??= await decide("godmode hook run moa", 10, payload)
      }
      if (tool === "task") {
        verdict ??= await decide("nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/pre-agent-task-context.nu", 10, payload)
        verdict ??= await decide("godmode hook run agent-governance", 10, payload)
      }
      if (tool === "write") {
        verdict ??= await decide("godmode hook run brainstorm", 10, payload)
      }
      // A blocking PreToolUse hook (pre-commit-gate) denies the call by
      // throwing, which is OpenCode's equivalent of Claude's block decision.
      if (verdict?.decision === "block") {
        throw new Error(verdict.reason ?? "[godmode] blocked by hook")
      }
    },
    "tool.execute.after": async (input, output) => {
      const tool = input.tool
      const payload = { ...input, ...output }
      if (tool === "bash") {
        await run("nu $CLAUDE_PLUGIN_ROOT/hooks/task-done-sync.nu", 15, payload)
        await run("nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/post-pipeline-step.nu", 10, payload)
        await run("godmode hook run auto-block", 10, payload)
        await run("godmode hook run ci-fix", 15, payload)
        await run("godmode hook run code-review", 10, payload)
        await run("godmode hook run wave-integration", 10, payload)
      }
      if (tool === "edit") {
        await run("nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/post-json-validate.nu", 10, payload)
        await run("nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/post-toml-validate.nu", 10, payload)
        await run("nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/post-yaml-validate.nu", 10, payload)
        await run("nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/post-nu-check.nu", 10, payload)
      }
      if (tool === "task") {
        await run("bash $CLAUDE_PLUGIN_ROOT/hooks/scripts/check-blocked.sh", 10, payload)
        await run("godmode hook run parallel-agents", 10, payload)
      }
      if (tool === "write") {
        await run("nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/post-json-validate.nu", 10, payload)
        await run("nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/post-toml-validate.nu", 10, payload)
        await run("nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/post-yaml-validate.nu", 10, payload)
        await run("nu $CLAUDE_PLUGIN_ROOT/hooks/scripts/post-nu-check.nu", 10, payload)
        await run("rust-script $CLAUDE_PLUGIN_ROOT/hooks/scripts/post-write-plan-ingest.rs", 15, payload)
      }
    },
  }
}

